package com.sherpa.model;
// default package

// Generated Nov 13, 2016 2:15:17 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

import com.sherpa.dto.RatingDto;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name = "rating", catalog = "sherpa")
public class Rating implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5140115175512178962L;
	private long ratingId;
	private Event event;
	private User user;
	private DateTime date;
	private String comment;
	private Integer rating;

	public Rating() {
	}

	public Rating(Event event, User user, DateTime date) {
		this.event = event;
		this.user = user;
		this.date = date;
	}

	public Rating(Event event, User user, DateTime date, String comment, Integer rating) {
		this.event = event;
		this.user = user;
		this.date = date;
		this.comment = comment;
		this.rating = rating;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rating_id", unique = true, nullable = false)
	public long getRatingId() {
		return this.ratingId;
	}

	public void setRatingId(long ratingId) {
		this.ratingId = ratingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_id", nullable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "date", nullable = false, length = 19)
	@Type(type="org.jadira.usertype.dateandtime.joda.PersistentDateTime")
	public DateTime getDate() {
		return this.date;
	}

	public void setDate(DateTime date) {
		this.date = date;
	}

	@Column(name = "comment", length = 512)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}
		
	public RatingDto generateDto(){
		RatingDto ratingDto = new RatingDto(this.getRatingId(), this.getEvent().getEventId(), this.getUser().getUserId(), this.getDate(), this.getComment(), this.getRating());
		return ratingDto;
	}

}
