package com.sherpa.dto;
// default package
// Generated Nov 13, 2016 2:15:17 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Achievement generated by hbm2java
 */
@Entity
@Table(name = "achievement", catalog = "sherpa")
public class Achievement implements java.io.Serializable {

	private Integer achievementId;
	private String imageUrl;
	private String description;
	private BigDecimal requirement;
	private Set<AchievementUserCross> achievementUserCrosses = new HashSet<AchievementUserCross>(0);

	public Achievement() {
	}

	public Achievement(String imageUrl, String description, BigDecimal requirement) {
		this.imageUrl = imageUrl;
		this.description = description;
		this.requirement = requirement;
	}

	public Achievement(String imageUrl, String description, BigDecimal requirement,
			Set<AchievementUserCross> achievementUserCrosses) {
		this.imageUrl = imageUrl;
		this.description = description;
		this.requirement = requirement;
		this.achievementUserCrosses = achievementUserCrosses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "achievement_id", unique = true, nullable = false)
	public Integer getAchievementId() {
		return this.achievementId;
	}

	public void setAchievementId(Integer achievementId) {
		this.achievementId = achievementId;
	}

	@Column(name = "image_url", nullable = false, length = 256)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "description", nullable = false, length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "requirement", nullable = false, precision = 7)
	public BigDecimal getRequirement() {
		return this.requirement;
	}

	public void setRequirement(BigDecimal requirement) {
		this.requirement = requirement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "achievement")
	public Set<AchievementUserCross> getAchievementUserCrosses() {
		return this.achievementUserCrosses;
	}

	public void setAchievementUserCrosses(Set<AchievementUserCross> achievementUserCrosses) {
		this.achievementUserCrosses = achievementUserCrosses;
	}

}
