package com.sherpa.dto;
// default package

// Generated Nov 13, 2016 2:15:17 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Currency generated by hbm2java
 */
@Entity
@Table(name = "currency", catalog = "sherpa", uniqueConstraints = @UniqueConstraint(columnNames = "iso"))
public class Currency implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3231399653545569101L;
	private Long currencyId;
	private String iso;
	private String name;
	private Set<Event> events = new HashSet<Event>(0);

	public Currency() {
	}

	public Currency(String iso, String name) {
		this.iso = iso;
		this.name = name;
	}

	public Currency(String iso, String name, Set<Event> events) {
		this.iso = iso;
		this.name = name;
		this.events = events;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "currency_id", unique = true, nullable = false)
	public Long getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Long currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "iso", unique = true, nullable = false, length = 3)
	public String getIso() {
		return this.iso;
	}

	public void setIso(String iso) {
		this.iso = iso;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currency")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
