package com.sherpa.dto;
// default package
// Generated Nov 13, 2016 2:15:17 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Experience generated by hbm2java
 */
@Entity
@Table(name = "experience", catalog = "sherpa", uniqueConstraints = @UniqueConstraint(columnNames = "user_id"))
public class Experience implements java.io.Serializable {

	private Integer experienceId;
	private User user;
	private int experience;
	private BigDecimal cumulativeRating;

	public Experience() {
	}

	public Experience(User user, int experience, BigDecimal cumulativeRating) {
		this.user = user;
		this.experience = experience;
		this.cumulativeRating = cumulativeRating;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "experience_id", unique = true, nullable = false)
	public Integer getExperienceId() {
		return this.experienceId;
	}

	public void setExperienceId(Integer experienceId) {
		this.experienceId = experienceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", unique = true, nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "experience", nullable = false)
	public int getExperience() {
		return this.experience;
	}

	public void setExperience(int experience) {
		this.experience = experience;
	}

	@Column(name = "cumulative_rating", nullable = false, precision = 1, scale = 1)
	public BigDecimal getCumulativeRating() {
		return this.cumulativeRating;
	}

	public void setCumulativeRating(BigDecimal cumulativeRating) {
		this.cumulativeRating = cumulativeRating;
	}

}
