package com.sherpa.dto;
// default package

// Generated Nov 13, 2016 2:15:17 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "sherpa")
public class Location implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6732388531857850713L;
	private Long locationId;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private String region;
	private Set<Event> eventsForEndLocationId = new HashSet<Event>(0);
	private Set<Event> eventsForStartLocationId = new HashSet<Event>(0);
	private Set<User> users = new HashSet<User>(0);

	public Location() {
	}

	public Location(BigDecimal latitude, BigDecimal longitude) {
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Location(BigDecimal latitude, BigDecimal longitude, String region, Set<Event> eventsForEndLocationId,
			Set<Event> eventsForStartLocationId, Set<User> users) {
		this.latitude = latitude;
		this.longitude = longitude;
		this.region = region;
		this.eventsForEndLocationId = eventsForEndLocationId;
		this.eventsForStartLocationId = eventsForStartLocationId;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "location_id", unique = true, nullable = false)
	public Long getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Long locationId) {
		this.locationId = locationId;
	}

	@Column(name = "latitude", nullable = false, precision = 10, scale = 8)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 10, scale = 8)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "region", length = 128)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationByEndLocationId")
	public Set<Event> getEventsForEndLocationId() {
		return this.eventsForEndLocationId;
	}

	public void setEventsForEndLocationId(Set<Event> eventsForEndLocationId) {
		this.eventsForEndLocationId = eventsForEndLocationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationByStartLocationId")
	public Set<Event> getEventsForStartLocationId() {
		return this.eventsForStartLocationId;
	}

	public void setEventsForStartLocationId(Set<Event> eventsForStartLocationId) {
		this.eventsForStartLocationId = eventsForStartLocationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
