package com.sherpa.dto;
// default package
// Generated Nov 13, 2016 2:15:17 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "report", catalog = "sherpa")
public class Report implements java.io.Serializable {

	private Integer reportId;
	private Event event;
	private User userByUserId;
	private User userBySherpaId;
	private Date date;
	private String comment;

	public Report() {
	}

	public Report(User userByUserId, User userBySherpaId, Date date, String comment) {
		this.userByUserId = userByUserId;
		this.userBySherpaId = userBySherpaId;
		this.date = date;
		this.comment = comment;
	}

	public Report(Event event, User userByUserId, User userBySherpaId, Date date, String comment) {
		this.event = event;
		this.userByUserId = userByUserId;
		this.userBySherpaId = userBySherpaId;
		this.date = date;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "report_id", unique = true, nullable = false)
	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_id")
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sherpa_id", nullable = false)
	public User getUserBySherpaId() {
		return this.userBySherpaId;
	}

	public void setUserBySherpaId(User userBySherpaId) {
		this.userBySherpaId = userBySherpaId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "comment", nullable = false, length = 512)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
